### ISSUE TITLE
doane.us year 0

### ISSUE THREAD

**Issue by ghost** [nutnetadmin/nutnet-data-tracker#108]
Not really bug, but doane.us in the file < full-biomass-09-April-2018.csv > has all subplots harvested in year 0 ... seems a bit like erroneous information (but excellent to look at spatial pattens/starting species pool!)

**Comment by nutnetadmin** [comment]
Hm, I am only getting one subplot harvested per plot.

(in database)
select year_trt, plot, count(distinct(subplot)) from full_biomass where site_code = 'doane.us'
group by plot, year_trt; 

did you notice that the block/plot numbering is a bit strange at doane? for example, plots 2 and 5 are in block 2, instead of in block 1.
